## Задание на повторение к домашке 2


In [3]:
import numpy as np

##### Задание 1

In [8]:
a = np.arange(12,24,1)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

##### Задание 2

In [9]:
?np.reshape

In [11]:
a1 = np.reshape(a,(2,6))
a1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [14]:
a2 = np.reshape(a,(3,4))
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [18]:
a3 = np.reshape(a,(12,1))
a3

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [17]:
a4 = np.reshape(a,(6,2))
a4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [19]:
a5 = np.reshape(a,(4,3))
a5

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

##### Задание 3

In [22]:
b1 = np.reshape(a, (12, -1))
b2 = np.reshape(a, (6, -1))
b3 = np.reshape(a, (4, -1))
b4 = np.reshape(a, (-1, 4))
b5 = np.reshape(a, (-1, 6))

##### Задание 4 - нельзя, так как у нас получается две меры:

In [29]:
np.shape(np.reshape(a, (1, 12)))

(1, 12)

##### Задание 5

In [55]:
a = np.random.normal(size=(3,4))
b = np.reshape(a, (a.size))
b

array([-0.42349776,  0.54157571,  0.60128721,  0.09946002, -1.26855019,
       -1.45124518,  0.87799821, -1.02562691,  0.60529822,  0.33441762,
       -1.2999253 ,  1.03195512])

##### Задание 6

In [64]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

##### Задание 7

In [73]:
b = np.arange(20, 1, -2).reshape(1,10)
np.array_equal(a,b)
# вывод: массивы нельзя назвать одинаковыми. Разница: второй массив (b) имеет вторую меру

False

##### Задание 8

In [74]:
?np.vstack

In [87]:
a = np.zeros((3,2))
b = np.ones((2,2))

c = np.vstack((a,b))
c.size

10

##### Задание 9

In [158]:
a = np.arange(0, 12, 1)
A = np.reshape(a, (4,3))
At = A.T
B = np.matmul(A,At)
np.shape(B)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [112]:
np.linalg.det(B)
#т.к. определитель матрицы B равен нулю, у неё нет обратной матрицы

0.0

##### Задание 10

In [115]:
np.random.seed(42)
# если я правильно понял, это оно

##### Задание 11

In [135]:
c = np.random.uniform(0,16,16).round().astype(int)
c

array([ 5,  5, 12, 10, 14,  8,  2, 11, 12,  9, 12,  8,  8,  7,  0,  2])

##### Задание 12

In [136]:
C = np.reshape(c, (4,4))
C

array([[ 5,  5, 12, 10],
       [14,  8,  2, 11],
       [12,  9, 12,  8],
       [ 8,  7,  0,  2]])

In [139]:
D = B + (C*10)
D

array([[ 55,  64, 143, 132],
       [154, 130, 106, 232],
       [143, 176, 269, 292],
       [112, 192, 212, 322]])

In [141]:
np.linalg.det(D)

42943400.00000005

In [149]:
D_inv = np.linalg.inv(D)
D_inv

array([[-0.00413521,  0.0092587 ,  0.00866117, -0.01282991],
       [-0.05671   , -0.01219792,  0.03401687,  0.00118854],
       [ 0.00362757, -0.00469828,  0.00751641, -0.0049181 ],
       [ 0.03286465,  0.00714615, -0.02824462,  0.01009748]])

In [155]:
mask = np.where(D_inv < 0, 0, 1)
mask

array([[0, 1, 1, 0],
       [0, 0, 1, 1],
       [1, 0, 1, 0],
       [1, 1, 0, 1]])

In [161]:
#если я правильно понял, то нужно так:
E = np.where(mask == 1, C, B)
E

array([[  5,   5,  12,  32],
       [ 14,  50,   2,  11],
       [ 12,  86,  12, 212],
       [  8,   7, 212,   2]])